type: docker
kind: pipeline
name: default

steps:
- name: auth0 - style
  image: rust:1.75.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add rustfmt
  - rustc --version
  - cargo --version
  - cargo fmt -- --version
  - cargo fmt --all -- --check

- name: auth0 - lint
  image: rust:1.75.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustup component add clippy
  - rustc --version
  - cargo --version
  - cargo clippy -- --version
  - cargo clippy --workspace --all-targets --all-features

- name: auth0 - test
  image: rust:1.75.0
  environment:
    RUST_BACKTRACE: full
  commands:
  - rustc --version
  - cargo --version
  - cargo test --workspace --all-features --release
